### ISSUE TITLE
Can't Add Description 

### ISSUE THREAD

**Issue by Zaldor** [etewiah/property_web_builder#44] opened 2017-12-03 18:10 UTC
Site installed and updated, configured to use italian languange, but when trying to add a property adding TITLE and Description to it doesn't seam to work (it does for english)
https://carusoimmobiliare.herokuapp.com/it/properties/for-sale/51/show
Default admin USR:PWD

**Comment by etewiah** [comment] 2017-12-03 18:37
Looks like it is a bug specific to Italian - let me just have a look now.

**Comment by etewiah** [comment] 2017-12-03 18:59
Okay, I see what the problem is.  I will push out a fix as soon as I can.

**Comment by Zaldor** [comment] 2017-12-03 19:46
Thanks!

Il dom 3 dic 2017, 19:59 Ed Tewiah <notifications@github.com> ha scritto:

**Comment by etewiah** [comment] 2017-12-04 15:17
Hi @Zaldor - I've pushed out a fix.  Please update to the latest build and let me know if it works.

**Comment by Zaldor** [comment] 2017-12-04 16:52
Seams to works. great!

**Comment by etewiah** [comment] 2017-12-04 17:11
Cool, I'll go ahead and close this issue then.

**Closed by etewiah** 2017-12-04 17:11 UTC
